// REPOSITORIES
export const FETCHING_REPOSITORIES = 'FETCHING_REPOSITORIES';
export const FETCHING_REPOSITORIES_SUCCESS = 'FETCHING_REPOSITORIES_SUCCESS';
export const FETCHING_REPOSITORIES_FAILURE = 'FETCHING_REPOSITORIES_FAILURE';